# The main CI of Hibernate Search is https://ci.hibernate.org/job/hibernate-search/.
# However, Hibernate Search builds run on GitHub actions regularly
# to check that it still works and can be used in GitHub forks.
# See https://docs.github.com/en/free-pro-team@latest/actions
# for more information about GitHub actions.

name: Hibernate Search contributor build

on:
  push:
    branches-ignore:
      - '5.*'
      - '4.*'
      - '3.*'
    tags: '*'
  pull_request:
    branches-ignore:
      - '5.*'
      - '4.*'
      - '3.*'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'hibernate/hibernate-search' }}

env:
  # Maven Wagon options are supposed to work around a problem on GitHub Actions' hosting platform, Azure
  # See https://github.com/actions/virtual-environments/issues/1499#issuecomment-691957310
  MAVEN_ARGS: "-e -B -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"
jobs:
  build:
    name: Build and test on Java 11
    runs-on: ubuntu-latest
    # Ignore dependabot PRs; we'll batch dependency upgrades manually in a single PR before we test them.
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get year/month for cache key
        id: get-date
        run: |
          echo "::set-output name=yearmonth::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven local repository
        uses: actions/cache@v2
        id: cache-maven
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-localrepo-${{ steps.get-date.outputs.yearmonth }}
      - name: Set up Maven
        run: ./mvnw -v
      - name: Docker cleanup
        run: ./ci/docker-cleanup.sh
      - name: Build and test
        run: ./mvnw $MAVEN_ARGS install -Pdist -Pcoverage -Pjqassistant
      - name: Upload test reports (if Maven failed)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-reports-java11
          path: './**/*-reports/'
      - name: Docker cleanup
        if: always()
        run: ./ci/docker-cleanup.sh
      - name: Omit produced artifacts from build cache
        run: rm -r ~/.m2/repository/org/hibernate/search
